# What is Pytorch
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

https://pytorch.org/docs/stable/torch.html

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38]])


#### Note 
An uninitialized matrix is declared, but does not contain definite known values before it is used. When an uninitialized matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.

In [3]:
x = torch.empty(5, 3)
print(x)


tensor([[9.9184e-39, 8.7245e-39, 9.2755e-39],
        [8.9082e-39, 9.9184e-39, 8.4490e-39],
        [9.6429e-39, 1.0653e-38, 1.0469e-38],
        [4.2246e-39, 1.0378e-38, 9.6429e-39],
        [9.2755e-39, 9.7346e-39, 1.0745e-38]])


In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4539, 0.6525, 0.4338],
        [0.9853, 0.3929, 0.0407],
        [0.5054, 0.8369, 0.4535],
        [0.6181, 0.8226, 0.0566],
        [0.4474, 0.4932, 0.8114]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.4992, -1.1066, -1.5764],
        [-1.8072, -0.4268, -0.2658],
        [ 1.9003, -0.5356,  1.6966],
        [ 0.1420, -0.7086, -0.3596],
        [ 0.3106,  0.0550, -1.4774]])


#### Note
torch.Size is in fact a tuple, so it supports all tuple operations.

In [8]:
print(x.size())

torch.Size([5, 3])


## Operations

In [9]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.0203, -0.2515, -0.7702],
        [-1.4368,  0.4280, -0.1312],
        [ 2.2998, -0.3257,  2.2328],
        [ 0.3449, -0.0718,  0.6179],
        [ 0.4115,  0.5908, -0.8954]])


In [10]:
print(torch.add(x, y))

tensor([[-0.0203, -0.2515, -0.7702],
        [-1.4368,  0.4280, -0.1312],
        [ 2.2998, -0.3257,  2.2328],
        [ 0.3449, -0.0718,  0.6179],
        [ 0.4115,  0.5908, -0.8954]])


In [11]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.0203, -0.2515, -0.7702],
        [-1.4368,  0.4280, -0.1312],
        [ 2.2998, -0.3257,  2.2328],
        [ 0.3449, -0.0718,  0.6179],
        [ 0.4115,  0.5908, -0.8954]])


In [12]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.0203, -0.2515, -0.7702],
        [-1.4368,  0.4280, -0.1312],
        [ 2.2998, -0.3257,  2.2328],
        [ 0.3449, -0.0718,  0.6179],
        [ 0.4115,  0.5908, -0.8954]])


#### Note
Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.


You can use standard NumPy-like indexing with all bells and whistles!

In [13]:
print(x[:, 1])

tensor([-1.1066, -0.4268, -0.5356, -0.7086,  0.0550])


### Resizing torch.view:

In [14]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8422])
-0.8421668410301208


## NumPy Bridge

The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA

In [20]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!